name: TestInternational
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: yuval <yuval.lerner@beonesolutions.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular:
  angular_components:
  intl:

dev_dependencies:
  build_runner:
  build_web_compilers:
  intl_translation:
    path: ../intl_translation
